data = [
    {"name": "instagram", "follower_count": 693,
        "description": "social media platform", "country": "United States"},
    {"name": "cristiano", "follower_count": 661,
        "description": "footballer", "country": "Portugal"},
    {"name": "leomessi", "follower_count": 506,
        "description": "footballer", "country": "Argentina"},
    {"name": "selenagomez", "follower_count": 418,
        "description": "musician and actress", "country": "United States"},
    {"name": "kyliejenner", "follower_count": 393,
        "description": "media personality", "country": "United States"},
    {"name": "therock", "follower_count": 393,
        "description": "actor and wrestler", "country": "United States"},
    {"name": "arianagrande", "follower_count": 375,
        "description": "musician and actress", "country": "United States"},
    {"name": "kimkardashian", "follower_count": 356,
        "description": "media personality", "country": "United States"},
    {"name": "beyonce", "follower_count": 311,
        "description": "musician and actress", "country": "United States"},
    {"name": "khloekardashian", "follower_count": 302,
        "description": "media personality", "country": "United States"},
    {"name": "nike", "follower_count": 300,
        "description": "sportswear brand", "country": "United States"},
    {"name": "justinbieber", "follower_count": 294,
        "description": "musician", "country": "Canada"},
    {"name": "kendalljenner", "follower_count": 287,
        "description": "media personality", "country": "United States"},
    {"name": "taylorswift", "follower_count": 281,
        "description": "musician", "country": "United States"},
    {"name": "natgeo", "follower_count": 278,
        "description": "magazine", "country": "United States"},
    {"name": "virat.kohli", "follower_count": 274,
        "description": "cricketer", "country": "India"},
    {"name": "jlo", "follower_count": 248,
        "description": "musician and actress", "country": "United States"},
    {"name": "neymarjr", "follower_count": 230,
        "description": "footballer", "country": "Brazil"},
    {"name": "nickiminaj", "follower_count": 225,
        "description": "musician", "country": "Trinidad and Tobago / USA"},
    {"name": "kourtneykardash", "follower_count": 218,
        "description": "media personality", "country": "United States"},
    {"name": "mileycyrus", "follower_count": 212,
        "description": "musician and actress", "country": "United States"},
    {"name": "katyperry", "follower_count": 204,
        "description": "musician", "country": "United States"},
    {"name": "zendaya", "follower_count": 178,
        "description": "actress and singer", "country": "United States"},
    {"name": "kevinhart4real", "follower_count": 177,
        "description": "comedian and actor", "country": "United States"},
    {"name": "realmadrid", "follower_count": 176,
        "description": "football club", "country": "Spain"},
    {"name": "iamcardib", "follower_count": 163,
        "description": "musician and actress", "country": "United States"},
    {"name": "kingjames", "follower_count": 159,
        "description": "basketball player", "country": "United States"},
    {"name": "ddlovato", "follower_count": 153,
        "description": "musician and actress", "country": "United States"},
    {"name": "badgalriri", "follower_count": 149,
        "description": "musician", "country": "Barbados / United States"},
    {"name": "chrisbrownofficial", "follower_count": 144,
        "description": "musician", "country": "United States"},
    {"name": "champagnepapi", "follower_count": 142,
        "description": "musician", "country": "Canada"},
    {"name": "fcbarcelona", "follower_count": 141,
        "description": "football club", "country": "Spain"},
    {"name": "ellendegeneres", "follower_count": 136,
        "description": "comedian and television host", "country": "United States"},
    {"name": "billieeilish", "follower_count": 124,
        "description": "musician", "country": "United States"},
    {"name": "k.mbappe", "follower_count": 124,
        "description": "footballer", "country": "France"},
    {"name": "championsleague", "follower_count": 121,
        "description": "football competition", "country": "Europe"},
    {"name": "gal_gadot", "follower_count": 108,
        "description": "actress", "country": "Israel"},
    {"name": "lalalalisa_m", "follower_count": 106,
        "description": "musician", "country": "South Korea"},
    {"name": "vindiesel", "follower_count": 103,
        "description": "actor", "country": "United States"},
    {"name": "nasa", "follower_count": 96.2,
        "description": "space agency", "country": "United States"},
    {"name": "narendramodi", "follower_count": 96.3,
        "description": "Prime Minister", "country": "India"},
    {"name": "shraddhakapoor", "follower_count": 94,
        "description": "actress", "country": "India"},
    {"name": "shakira", "follower_count": 92.5,
        "description": "musician", "country": "Colombia"},
    {"name": "priyankachopra", "follower_count": 92.3,
        "description": "actress", "country": "India"},
    {"name": "nba", "follower_count": 90.7,
        "description": "professional basketball league", "country": "United States"},
    {"name": "snoopdogg", "follower_count": 88.3,
        "description": "musician", "country": "United States"},
    {"name": "davidbeckham", "follower_count": 88.1,
        "description": "former footballer", "country": "United Kingdom"},
    {"name": "dualipa", "follower_count": 87.6,
        "description": "musician", "country": "United Kingdom"},
    {"name": "jennierubyjane", "follower_count": 87.3,
        "description": "musician", "country": "South Korea"},
    {"name": "aliaabhatt", "follower_count": 86.3,
        "description": "actress", "country": "India"},
]
